# Generated by Django 5.0.1 on 2025-12-02 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
        ("tenants", "0007_client_alter_feature_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="page",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="page",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages",
                to="tenants.client",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="page",
            unique_together={("tenant", "slug")},
        ),
    ]
