# Generated by Django 5.0.1 on 2025-11-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("card", "Carte bancaire"),
                            ("bank_transfer", "Virement bancaire"),
                            ("paypal", "PayPal"),
                            ("stripe", "Stripe"),
                            ("check", "Chèque"),
                            ("cash", "Espèces"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, help_text="Disponible pour les tenants"
                    ),
                ),
                (
                    "requires_validation",
                    models.BooleanField(
                        default=False, help_text="Nécessite validation manuelle"
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Configuration spécifique (clés API, etc.)",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icône ou emoji", max_length=50, null=True
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Ordre d'affichage"),
                ),
                (
                    "fee_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Commission en %",
                        max_digits=5,
                    ),
                ),
                (
                    "fee_fixed",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Commission fixe",
                        max_digits=10,
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Montant minimum",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Montant maximum",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mode de paiement",
                "verbose_name_plural": "Modes de paiement",
                "db_table": "payment_methods",
                "ordering": ["order", "name"],
            },
        ),
    ]
