# Generated by Django 5.0.1 on 2025-12-01 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_alter_pricingplan_options_pricingplan_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={"ordering": ["-created_at", "-id"]},
        ),
    ]
