# Generated by Django 5.0.1 on 2025-11-27 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_add_deleted_at_soft_delete"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-created_at"]},
        ),
    ]
