# Generated by Django 5.0.1 on 2025-12-01 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_replace_is_premium_with_plans"),
        ("tenants", "0005_alter_user_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Identifiant unique de la fonctionnalité",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Nom affiché de la fonctionnalité", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description de la fonctionnalité"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("development", "En développement"),
                            ("beta", "Bêta"),
                            ("stable", "Stable"),
                            ("deprecated", "Déprécié"),
                        ],
                        default="development",
                        max_length=20,
                    ),
                ),
                (
                    "requires_setup",
                    models.BooleanField(
                        default=False, help_text="Nécessite une configuration"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Catégorie de la fonctionnalité",
                        max_length=50,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Ordre d'affichage"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Fonctionnalité disponible"
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "available_plans",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Plans tarifaires qui donnent accès à cette feature. Si vide, accessible à tous.",
                        related_name="available_features",
                        to="billing.pricingplan",
                    ),
                ),
            ],
            options={
                "db_table": "features",
                "ordering": ["category", "order", "label"],
            },
        ),
        migrations.CreateModel(
            name="UserFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("enabled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes sur l'activation de cette fonctionnalité",
                    ),
                ),
                (
                    "enabled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="features_enabled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_features",
                        to="tenants.feature",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enabled_features",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_features",
                "ordering": ["-enabled_at"],
                "unique_together": {("user", "feature")},
            },
        ),
    ]
