# Generated by Django 5.0.1 on 2025-10-13 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="templates/thumbnails/"
                    ),
                ),
                ("preview_url", models.URLField(blank=True, null=True)),
                ("structure", models.JSONField(blank=True, default=dict)),
                ("default_settings", models.JSONField(blank=True, default=dict)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("vtc", "VTC"),
                            ("business", "Business"),
                            ("minimal", "Minimal"),
                            ("modern", "Modern"),
                            ("classic", "Classic"),
                        ],
                        default="vtc",
                        max_length=50,
                    ),
                ),
                ("is_premium", models.BooleanField(default=False)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("usage_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "templates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file_name", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=100)),
                ("path", models.CharField(max_length=500)),
                ("disk", models.CharField(default="local", max_length=50)),
                ("size", models.BigIntegerField()),
                (
                    "collection",
                    models.CharField(
                        choices=[
                            ("images", "Images"),
                            ("documents", "Documents"),
                            ("videos", "Videos"),
                            ("audio", "Audio"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("alt_text", models.CharField(blank=True, max_length=255, null=True)),
                ("order", models.IntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "media",
                "ordering": ["-created_at"],
            },
        ),
    ]
