# Generated by Django 5.0.1 on 2025-12-02 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
        ("tenants", "0008_delete_tenant"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="service",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="service",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenants.client"
            ),
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.UniqueConstraint(
                condition=models.Q(("slug__isnull", False)),
                fields=("slug",),
                name="unique_slug_when_not_null",
            ),
        ),
    ]
