# Generated by Django 5.0.1 on 2025-12-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "20251127_010759_add_template_variables"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="template",
            name="preview_url",
        ),
        migrations.RemoveField(
            model_name="template",
            name="thumbnail",
        ),
        migrations.AddField(
            model_name="template",
            name="css_content",
            field=models.TextField(
                blank=True, help_text="CSS content of the template", null=True
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="html_content",
            field=models.TextField(
                blank=True, help_text="HTML content of the template", null=True
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                help_text="Image de prévisualisation du template",
                null=True,
                upload_to="templates/previews/",
            ),
        ),
    ]
