# Generated by Django 5.0.1 on 2025-12-02 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "20251128_remove_template_preview_url_and_more"),
        ("tenants", "0007_client_alter_feature_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.client",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="slug",
            field=models.SlugField(max_length=255),
        ),
    ]
