# Generated by Django 5.0.1 on 2025-11-27 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0005_alter_user_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Identifiant unique du bloc (ex: text, image, video)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Nom affiché (ex: Bloc Texte, Bloc Image)",
                        max_length=100,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Nom de l'icône (ex: text, image, video)",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("content", "Contenu"),
                            ("layout", "Mise en page"),
                            ("media", "Médias"),
                            ("custom", "Personnalisé"),
                        ],
                        default="content",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description du bloc", null=True
                    ),
                ),
                (
                    "schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Schéma JSON pour validation",
                    ),
                ),
                (
                    "default_styles",
                    models.JSONField(
                        blank=True, default=dict, help_text="Styles par défaut du bloc"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Activer/désactiver ce type de bloc"
                    ),
                ),
                (
                    "requires_premium",
                    models.BooleanField(
                        default=False, help_text="Nécessite un plan premium"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Ordre d'affichage dans la palette"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Type de Bloc",
                "verbose_name_plural": "Types de Blocs",
                "db_table": "block_types",
                "ordering": ["category", "order", "label"],
            },
        ),
        migrations.CreateModel(
            name="BlockTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "block_data",
                    models.JSONField(default=dict, help_text="Données du bloc"),
                ),
                (
                    "block_styles",
                    models.JSONField(
                        blank=True, default=dict, help_text="Styles du bloc"
                    ),
                ),
                (
                    "block_settings",
                    models.JSONField(
                        blank=True, default=dict, help_text="Paramètres du bloc"
                    ),
                ),
                (
                    "is_global",
                    models.BooleanField(
                        default=False,
                        help_text="Template disponible pour tous les tenants",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Si null, template global",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
                (
                    "block_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blocks.blocktype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template de Bloc",
                "verbose_name_plural": "Templates de Blocs",
                "db_table": "block_templates",
                "ordering": ["-created_at"],
            },
        ),
    ]
