# Generated by Django 5.0.1 on 2025-12-02 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocks", "0003_remove_blocktype_requires_premium"),
        ("tenants", "0007_client_alter_feature_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blocktemplate",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Si null, template global",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.client",
            ),
        ),
    ]
