# Generated by Django 5.0.1 on 2025-11-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0002_add_homepage_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="stripe_enabled",
            field=models.BooleanField(
                default=False, help_text="Activer les paiements Stripe"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="stripe_mode",
            field=models.CharField(
                choices=[("test", "Test"), ("live", "Production")],
                default="test",
                help_text="Mode Stripe",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="stripe_public_key",
            field=models.CharField(
                blank=True,
                help_text="Clé publique Stripe (pk_test_... ou pk_live_...)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="stripe_secret_key",
            field=models.CharField(
                blank=True,
                help_text="Clé secrète Stripe (sk_test_... ou sk_live_...)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="stripe_webhook_secret",
            field=models.CharField(
                blank=True,
                help_text="Secret du webhook Stripe (whsec_...)",
                max_length=255,
            ),
        ),
    ]
