# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='public_homepage_blocks',
            field=models.JSONField(blank=True, default=list, help_text="Blocs de contenu pour la page d'accueil publique"),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='public_homepage_meta_title',
            field=models.CharField(blank=True, default='VTCBuilder - Le WordPress des chauffeurs VTC', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='public_homepage_meta_description',
            field=models.TextField(blank=True, default='Plateforme complète pour créer et gérer votre site VTC professionnel'),
        ),
    ]

