# Generated by Django 5.0.1 on 2025-11-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_invitationtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="Date de suppression (soft delete)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("trial", "Trial"),
                    ("cancelled", "Cancelled"),
                    ("deleted", "Deleted"),
                ],
                default="trial",
                max_length=20,
            ),
        ),
    ]
