# Generated by Django 5.0.1 on 2025-12-02 00:19

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0006_replace_is_premium_with_plans"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
        migrations.AlterModelOptions(
            name="feature",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="userfeature",
            options={},
        ),
        migrations.RemoveField(
            model_name="feature",
            name="available_plans",
        ),
        migrations.RemoveField(
            model_name="feature",
            name="category",
        ),
        migrations.RemoveField(
            model_name="feature",
            name="label",
        ),
        migrations.RemoveField(
            model_name="feature",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="feature",
            name="order",
        ),
        migrations.RemoveField(
            model_name="feature",
            name="requires_setup",
        ),
        migrations.RemoveField(
            model_name="feature",
            name="status",
        ),
        migrations.RemoveField(
            model_name="userfeature",
            name="enabled_at",
        ),
        migrations.RemoveField(
            model_name="userfeature",
            name="enabled_by",
        ),
        migrations.RemoveField(
            model_name="userfeature",
            name="is_enabled",
        ),
        migrations.RemoveField(
            model_name="userfeature",
            name="notes",
        ),
        migrations.AddField(
            model_name="feature",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="userfeature",
            name="granted_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="feature",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="feature",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="feature",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="userfeature",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_features",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelTable(
            name="domain",
            table=None,
        ),
        migrations.AlterField(
            model_name="domain",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domains",
                to="tenants.client",
            ),
        ),
        migrations.AlterField(
            model_name="invitationtoken",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="tenants.client",
            ),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
