# Generated by Django 5.0.1 on 2025-12-02 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_alter_invoice_tenant_alter_payment_tenant_and_more"),
        ("blocks", "0004_alter_blocktemplate_tenant"),
        ("media", "20251129_alter_media_tenant_alter_template_slug"),
        ("pages", "0002_alter_page_unique_together_alter_page_tenant_and_more"),
        ("tenants", "0007_client_alter_feature_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tenant",
        ),
    ]
