# Generated by Django 5.0.1 on 2025-12-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0008_delete_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="email",
            field=models.EmailField(
                blank=True, max_length=255, null=True, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="metadata",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Métadonnées"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="plan",
            field=models.CharField(
                blank=True,
                default="free",
                max_length=50,
                null=True,
                verbose_name="Plan",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="primary_color",
            field=models.CharField(
                blank=True,
                default="#3B82F6",
                max_length=7,
                null=True,
                verbose_name="Couleur primaire",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="secondary_color",
            field=models.CharField(
                blank=True,
                default="#6B7280",
                max_length=7,
                null=True,
                verbose_name="Couleur secondaire",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="settings",
            field=models.JSONField(blank=True, default=dict, verbose_name="Paramètres"),
        ),
        migrations.AddField(
            model_name="client",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=100, null=True, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="status",
            field=models.CharField(
                blank=True,
                default="active",
                max_length=50,
                null=True,
                verbose_name="Statut",
            ),
        ),
    ]
