# Generated by Django 5.0.1 on 2025-12-03 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0009_client_email_client_metadata_client_plan_and_more"),
    ]

    operations = []
