# Generated by Django 5.0.1 on 2025-11-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_paymentmethod"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pricingplan",
            options={"ordering": ["order", "price_monthly"]},
        ),
        migrations.AddField(
            model_name="pricingplan",
            name="order",
            field=models.IntegerField(
                default=0, help_text="Ordre d'affichage sur le site public"
            ),
        ),
    ]
