# Generated by Django 5.0.1 on 2025-12-02 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_invoicetemplate"),
        ("tenants", "0007_client_alter_feature_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="tenants.client",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="tenants.client",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="tenant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription",
                to="tenants.client",
            ),
        ),
    ]
